"""Add disease detection columns

Revision ID: 4ecf223bcfae
Revises: 38505036efa9
Create Date: 2025-05-25 22:43:44.596700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ecf223bcfae'
down_revision = '38505036efa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disease_name', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('disease_probability', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('disease_details', sa.String(length=1024), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.drop_column('disease_details')
        batch_op.drop_column('disease_probability')
        batch_op.drop_column('disease_name')

    # ### end Alembic commands ###
